language: node_js
node_js:
  - 10
before_script:
  - yarn install
  - yarn lerna bootstrap
  - yarn lerna run --scope @buy1s/*-service yarn build
  - yarn lerna run --scope @buy1s/*-service yarn test:ci