language: node_js
node_js:
  - 10
services:
  - mongodb
  - redis-server
before_script:
  - yarn install
  - yarn lerna bootstrap
  - yarn lerna run --scope @buy1s/*-service build
script: yarn lerna run --scope @buy1s/*-service test:ci